source_id: SRC06
grain: mbacc_gateway

expected_columns:
  - gateway_code
  - gateway_name
  - alternate_name
  - source_authority
  - is_current
  - source_checked_date

business_key:
  - gateway_code

geography_key: null

accepted_values:
  source_authority:
    - GMCA

  is_current:
    - "true"

expected_gateway_codes:
  - MBACC01
  - MBACC02
  - MBACC03
  - MBACC04
  - MBACC05
  - MBACC06
  - MBACC07
