source_id: SRC02
grain: academic_year_lad_ssa_sex_ethnicity_level

expected_columns:
  - time_period
  - time_identifier
  - geographic_level
  - country_code
  - country_name
  - region_code
  - region_name
  - lad_code
  - lad_name
  - ssa_tier_1
  - sex
  - ethnicity_major
  - apps_level
  - starts
  - achievements

business_key:
  - time_period
  - lad_code
  - ssa_tier_1
  - sex
  - ethnicity_major
  - apps_level

value_fields:
  - starts
  - achievements

special_values:
  low: low_non_zero

geography_key: lad_code

scope:
  geographic_level: Local authority district
  geography_codes:
    - E08000001
    - E08000002
    - E08000003
    - E08000004
    - E08000005
    - E08000006
    - E08000007
    - E08000008
    - E08000009
    - E08000010

accepted_values:
  sex:
    - Female
    - Male
    - Total

  ethnicity_major:
    - Asian / Asian British
    - Black / African / Caribbean / Black British
    - Mixed / Multiple ethnic groups
    - Other ethnic group
    - Total
    - Unknown
    - White

  apps_level:
    - Advanced Apprenticeship
    - Higher Apprenticeship
    - Intermediate Apprenticeship
    - Total

expected_special_values:
  starts:
    - low

  achievements:
    - low
